package com.example.highplattest.systest;


public class SysTest0 {
	/**
	 * 综合用例说明
	 * SysTest1:磁卡性能、压力
	 * SysTest2:射频性能、压力
	 * SysTest3:IC性能、压力
	 * SysTest4:WLAN性能、压力
	 * SysTest5:BT性能、压力
	 * |||SysTest6:Eth性能、压力
	 * SysTest7:无线性能、压力
	 * SysTest8:Modem性能、压力
	 * SysTest9:打印性能、压力
	 * SysTest10:物理串口性能、压力
	 * SysTest11:reboot压力
	 * SysTest12:SD卡（U盘）性能、压力
	 * SysTest13:wifi/wifi探针
	 * SysTest14:RTC综合
	 * SysTest15:LCD屏幕测试
	 * SysTest16:USB串口性能、压力
	 * SysTest17:磁卡/SMART
	 * |||SysTest18:磁卡/LAN
	 * SysTest19:磁卡/BT
	 * SysTest20:WLM/磁卡
	 * SysTest21:磁卡/MDM
	 * SysTest22:磁卡/触屏
	 * SysTest23:磁卡/打印
	 * SysTest24:RF/ICSAM
	 * SysTest25:触屏/RF
	 * |||SysTest26:SMART/LAN
	 * SysTest27:SMART/BT
	 * SysTest28:SMART/WLM
	 * SysTest29:SMART/MDM
	 * SysTest30:SMART/SD卡
	 * SysTest31:SMART/打印
	 * SysTest32:WIFI/BT
	 * |||SysTest33:WLAN/ETH
	 * SysTest34:WLAN/无线
	 * SysTest35:WLM/BT
	 * SysTest36:mpos/NDK密钥
	 * SysTest37:打印/BT
	 * |||SysTest38:LAN/WLM
	 * |||SysTest39:MDM/LAN
	 * |||SysTest40:打印/LAN
	 * SysTest41:无线/MDM
	 * SysTest42:Dongle综合测试
	 * SysTest43:打印/WLM
	 * SysTest44:打印/MDM交叉测试
	 * |||SysTest45:串口/以太网
	 * SysTest46:打印/SD卡(U盘)
	 * SysTest47:触屏/打印
	 * SysTest48:电池信息/打印
	 * SysTest49:电池信息/WLM
	 * SysTest50:电池信息/WIFI
	 * SysTest51:电池信息/BT
	 * SysTest52:Wifi_Ap性能、压力
	 * SysTest53:WLAN/AP
	 * SysTest54:三界面卡测试
	 * SysTest55:安全综合测试
	 * SysTest56:扫码综合测试
	 * SysTest57:Memory综合
	 * SysTest58:菲波纳契数列
	 * SysTest59:打印/键盘
	 * SysTest60:磁卡/键盘
	 * SysTest61:射频/键盘
	 * SysTest62:N900蓝牙底座
	 * SysTest63:NFC性能、压力
	 * SysTest64:NFC/ICSAM
	 * SysTest65:NFC/打印
	 * SysTest66:NFC/磁卡
	 * SysTest67:NFC/触屏
	 * SysTest68:NFC/WLM
	 * SysTest69:NFC/WLAN
	 * SysTest70:NFC/SD(U盘)
	 * SysTest71:NFC/BT
	 * SysTest72:GPS/SMART
	 * SysTest73:获取安全寄存器状态压力
	 * SysTest74:N910底座测试
	 * SysTest75:实际应用流程测试
	 * SysTest76:网络推送延迟稳定性测试
	 * SysTest77:pin压力
	 * SysTest78:外接密码键盘功能,压力
	 * SysTest79:安卓扫描枪扫条形码
	 * SysTest80:BT性能、压力(BLE蓝牙)
	 * SysTest81:农行客诉问题复现
	 * SysTest82:签名板测试
	 * SysTest87:(SoftEngine)startDecode方式扫码综合
	 * SysTest88:(ScanUtil)startYUVDecode方式扫码综合
	 * SysTest96:【重启压力】重启-安装密钥压力测试
	 * SysTest97:【EMV】EMV优化综合案例
	 * SysTest100:多模块并发（浅并发）
	 * SysTest101:K21多模块并发（深并发）
	 * SysTest102:K21多模块并发(深并发+浅并发)
	 * SysTest103:wifi底座新增功能
	 * SysTest104:SoftEngine方式扫码综合
	 * SysTest108：触屏综合
	 * SysTest109:【EMV】Emv相关模块并发测试
	 * SysTest110:外接SP100密码键盘测试(海外版_X5支持)
	 */

}
